In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/pleiades/pleiades-names.csv")

In [3]:
df.columns

Index(['authors', 'bbox', 'created', 'creators', 'currentVersion',
       'description', 'extent', 'id', 'locationPrecision', 'maxDate',
       'minDate', 'modified', 'nameAttested', 'nameLanguage',
       'nameTransliterated', 'path', 'pid', 'reprLat', 'reprLatLong',
       'reprLong', 'tags', 'timePeriods', 'timePeriodsKeys',
       'timePeriodsRange', 'title', 'uid'],
      dtype='object')

In [4]:
df_filtered = df[["nameAttested", "nameLanguage", "nameTransliterated", "reprLat", "reprLong", "title"]]
df_filtered.head(10)

nameAttested nameLanguage nameTransliterated    reprLat  reprLong  \
0             NaN          NaN          Consabura  39.460299 -3.606772   
1             NaN          NaN          Consabrum  39.460299 -3.606772   
2             NaN          NaN          Kondabora  39.460299 -3.606772   
3  Consaburrenses           la     Consaburrenses  39.460299 -3.606772   
4     Contestania           la        Contestania  38.500000 -1.500000   
5             NaN          NaN         Contestani  38.500000 -1.500000   
6             NaN          NaN            Dianium  38.842795  0.107511   
7             NaN          NaN     Hemeroskopeion  38.842795  0.107511   
8           Dénia  ca-valencia       Dénia, Denia        NaN       NaN   
9             NaN          NaN              Ebura  37.463838 -3.924959   

            title  
0       Consabura  
1       Consabrum  
2       Kondabora  
3  Consaburrenses  
4     Contestania  
5      Contestani  
6         Dianium  
7  Hemeroskopeion  
8           Dénia  
9           Ebura

In [5]:
namesTransliterated = np.array(df["nameTransliterated"], dtype=str)
namesTransliterated

array(['Consabura', 'Consabrum', 'Kondabora', ..., 'Amaltheum',
       'Lago del Matese', 'Anfiteatro di Alba Fucens'], dtype='<U413')

In [6]:
names = np.array(pd.read_csv("../data/output/phi0474.phi056.perseus-lat1/sorted_locs.csv", quotechar='"'), dtype=str)[:, 0]
names

array(['Alexandrium', 'Allobrogibus', 'Alyzia', 'Arpinati', 'Astura',
       'Athens', 'Attici Ficuleano house', 'Brindisium', 'Brundisium',
       'Caesars', 'Campania', 'Capua', 'Cilicia', 'Corcyra', 'Corduba',
       'Cumanum', 'Cyprum', 'Dertona', 'Dyrrhachium', 'Eporedia',
       'Formium', 'Gallia', 'Hispania', 'Iconium', 'Intimilium',
       'Lanuvium', 'Laterium', 'Latium', 'Laudicea', 'Lepidus', 'Maium',
       'Menturnis', 'Mopsuhestia', 'Mytilens', 'Narona', 'Neapolium',
       'Parma', 'Patra', 'Perga', 'Pindenessus', 'Pindenissus',
       'Pollentia', 'Pompeiano house', 'Pomptinum', 'Ponte', 'Pyramus',
       'Regium', 'Rhodium', 'Roma', 'Sicilia', 'Sidae', 'Syria',
       'Tadolics', 'Tarsium', 'Thessalonica', 'Tusculanum', 'Velia',
       'Vercells', 'Voconium'], dtype='<U22')

In [7]:
np.isin(names, namesTransliterated)

array([False, False,  True, False,  True,  True, False, False,  True,
       False,  True,  True,  True,  True,  True, False, False,  True,
        True,  True, False,  True,  True,  True, False,  True,  True,
        True, False, False, False,  True, False, False,  True, False,
        True,  True, False, False, False,  True, False, False, False,
       False,  True, False, False,  True, False,  True, False, False,
        True, False,  True, False, False])

In [8]:
for name in names:
    index_list = np.where(name == namesTransliterated)[0]
    if len(index_list) > 0:
        print(index_list)
        print(df[["title", "reprLat", "reprLong"]].iloc[index_list])

[21925]
        title    reprLat   reprLong
21925  Alyzia  38.713373  20.951657
[ 6045 11520 31183]
        title    reprLat   reprLong
6045   Astura        NaN        NaN
11520  Astura  41.408855  12.765272
31183  Astura        NaN        NaN
[19957]
        title  reprLat  reprLong
19957  Athens      NaN       NaN
[12174]
            title    reprLat   reprLong
12174  Brundisium  40.638663  17.942912
[11550 27644]
          title  reprLat  reprLong
11550  Campania    41.25     14.25
27644  Campania      NaN       NaN
[11562]
       title    reprLat   reprLong
11562  Capua  41.086092  14.250207
[ 4371 15391 25699 27493]
         title  reprLat  reprLong
4371   Cilicia    38.25     35.75
15391  Cilicia      NaN       NaN
25699  Cilicia      NaN       NaN
27493  Cilicia      NaN       NaN
[21969 21972]
         title    reprLat  reprLong
21969  Corcyra  39.606285  19.91558
21972  Corcyra  39.750000  19.75000
[20613]
         title    reprLat  reprLong
20613  Corduba  37.884683 -4.779171